### ISSUE TITLE
Not synchronized

### ISSUE THREAD

**Issue by sedatcakir** [framer/plugins#111]
Hi guys,

**Describe the bug**
The updated google spreadsheets data in Framer is not synchronized via the sync button to update it. I think there are delays or problems in the service.

**To Reproduce**
1. Go to 'Framer'
2. Click on 'Sync'
3. The bar rotates in an infinite loop.

Thank you very much. 🙏

**Comment by triozer** [comment]
Hi @sedatcakir, we've been working on fixing synchronization issues in #109, hopefully it should fix yours too. When it's deployed, we'll let you know.

Please, re-open this issue if there are any issues after!
