### ISSUE TITLE
Google Sheets errors when re-syncing number fields

### ISSUE THREAD

**Issue by triozer** [framer/plugins#143]
**Describe the bug**

When syncing a spreadsheet with number fields it seems like the value is not transformed in a `number`.

> Error: Expected a number value for field: Number, in item: XXX

**To Reproduce**
Syncing a basic sheet with just two columns of a number and a string errored with Error: Expected a number value for field: Number, in item: XXX

**Expected behavior**
For number-type column the field data value should be of type `number`

### Community Posts

- https://www.framer.community/c/plugins/google-sheets-sync-not-working

**Comment by tom-james-watson** [comment]
https://www.framer.community/c/plugins/google-sheets-sync-not-working
