### ISSUE TITLE
Airtable Plugin - Boolean Fields not syncing

### ISSUE THREAD

**Issue by notnotDudu** [framer/plugins#152]
Describe the bug
The Airtable Plugin in Framer does not update Boolean field types. When changes are made to Boolean fields in Airtable, the updates are not reflected in the Framer CMS.

To Reproduce

Go to the Airtable base connected to the Framer CMS.
Edit a Boolean field in the Airtable base (e.g., toggle it on or off).
Return to Framer CMS and refresh the content or sync data with the Airtable Plugin.
Observe that the Boolean field changes made in Airtable are not reflected in the Framer CMS.
Expected behavior
Changes made to Boolean fields in Airtable should sync correctly and appear in the Framer CMS when the data is refreshed or synced.

Additional context
This issue appears specific to Boolean field types; other data types (e.g., text, numbers) sync correctly between Airtable and Framer CMS. Ensure that the Airtable Plugin is up-to-date and configured correctly.

**Comment by triozer** [comment]
Hey @notnotDudu, this issue has been fixed in the following PR https://github.com/framer/plugins/pull/147. Thanks for reporting it!

**Comment by notnotDudu** [comment]
Hey Cedric, 

When will this resolution be reflected on the plugin?


-- 
Kindest Regards, 
Cook from @DuduAgency


￼
