### ISSUE TITLE
Notion CMS plugin : code block wrongly converted to inline code

### ISSUE THREAD

**Issue by damien-schneider** [framer/plugins#73]
**Describe the bug**
A created code block in a Notion page, is converted to inline code in the framer CMS instead of a code block

**To Reproduce**
1. Create a Notion database
2. Add a page with some code block content (not inline code)
3. Link the database to a CMS collection thanks to the notion plugin
4. Sync content to a CMS Field
5. Check the code block is wrongly converted to inline code instead

![CleanShot 2024-10-03 at 10 06 47](https://github.com/user-attachments/assets/bdafe61c-0e68-4fd6-8a19-7e29d8916745)

**Expected behavior**
The code should be converted to code block in the CMS collection
![CleanShot 2024-10-03 at 10 10 00](https://github.com/user-attachments/assets/97ac9008-2a2e-439c-8e3a-c8a6a269186a)

**Comment by niekert** [comment]
Thanks! Can confirm this is a bug. Seems like its not specific to the Notion plugin but on the Framer side. We're adding a ticket to support code blocks in HTML and can keep this issue open for the time being

**Comment by alecmev** [comment]
The fix is live!

**Comment by damien-schneider** [comment]
Thanks! I’ll start using it right away then!
