### ISSUE TITLE
Allow adding more than 30 fields in a CMS collection

### ISSUE THREAD

**Issue by madebyisaacr** [framer/plugins#82]
**Describe your use case**
I am trying to build a CMS plugin that allows importing more than 30 fields from Notion, Airtable, or Google Sheets but cannot because there is a limit of 30 fields per CMS collection.

**Describe the solution you'd like**
Remove the limit or increase it to something like 50 or 100 fields.

**Describe alternatives you've considered**
A workaround that I might use, if enough users of my plugin are having problems with the field limit, is importing the collection as 2 CMS collections with the same slugs but different fields, and linking them together with a reference field.

Then you can effectively have up to 59 fields because the reference field would allow using fields from the second CMS collection in pages for the first CMS collection.

Regular CMS collections do not have a limit on the number of fields, so there should not be a limit on plugin-managed CMS collection either.

**Comment by niekert** [comment]
The 30 field limit has been removed now!
