### ISSUE TITLE
framer.subscribeToImage() errors in image mode plugin

### ISSUE THREAD

**Issue by madebyisaacr** [framer/plugins#9]
**Describe the bug**
Using the `framer.subscribeToImage()` function when editing images causes this error in the console:
```
error: [ActivePlugin] Cannot subscribe to topic: image, while in mode: image
```

**To Reproduce**
1. Run the Threshold plugin from https://github.com/framer/plugins/tree/main/plugins/threshold
3. Open the developer console
4. Add an image to a frame, then launch the Developer Plugin from the image plugins menu.
5. Check the console for an error.

**Expected behavior**
`framer.subscribeToImage()` should work when editing images.

**Additional context**
I think the issue is that the plugin mode (`framer.getMode()`) is "image" when it should be "editImage". The docs say that "image" doesn't have access to the current image and "editImage" does, but it doesn't seem to be possible to get the development plugin to use "editImage" mode instead of "image" right now. Even when "image" is not included in the list of modes in framer.json.

**Comment by madebyisaacr** [comment]
To clarify, the error is only when launching the plugin from the image plugins menu. When launched from the action menu in "default" mode, `framer.subscribeToImage()` works fine.

**Comment by huntercaron** [comment]
@jonastreub @niekert is this expected?

**Comment by niekert** [comment]
Oh nice catch. This should indeed not throw an error.

**Comment by niekert** [comment]
This should no longer be happening - it was solved a while back. Feel free reopen if you still encounter issues
